"""
Django settings for facemon project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from mongoengine import connect
import json

from lib.TGMT.TGMTfile import MkDir
#import tensorflow as tf
#from keras.models import load_model

# setup tensorflow gpu config here
#ref: https://medium.com/@starriet87/tensorflow-2-0-wanna-limit-gpu-memory-10ad474e2528
#ref issue: https://github.com/tensorflow/tensorflow/issues/24496

# gpus = tf.config.experimental.list_physical_devices('GPU')
# if gpus:
#     try:
#         for gpu in gpus:
#             tf.config.experimental.set_memory_growth(gpu, True)
#     except RuntimeError as e:
#         print(e)




# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IS_LINUX = BASE_DIR[0] == '/'
IS_WINDOWS = BASE_DIR[1] == ':'

SLASH = '/'
if IS_WINDOWS:
    SLASH = '\\'
    
PROJECT_DIR = os.path.join(BASE_DIR, "..", "..")
DEBUG = True

BUILD_MODE = "debug"
if os.path.exists(os.path.join(PROJECT_DIR, "release")):
    DEBUG = False
    BUILD_MODE = "release"

SETTINGS = None
SETTING_PATH = os.path.join(BASE_DIR, "yolo", "settings.json")
with open(SETTING_PATH, encoding='utf-8') as f:
    SETTINGS = json.load(f)

VERSION = SETTINGS["version"]


THRESHOLD = 67
THRESHOLD_ADD_SAMPLE = 76
TIME_BETWEEN_ADD_SAMPLE = 60
SESSION_TIME = 60
if(DEBUG): SESSION_TIME = 1

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SETTINGS["secrect_key"]

# SECURITY WARNING: don't run with debug turned on in production!

DB_SETTING = SETTINGS["mongodb"][BUILD_MODE]

ALLOWED_HOSTS = ['*']
ADMIN_ENABLED = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'mongoengine',
    'rest_framework',
    'corsheaders',
    'api',
    'web',
    'django_crontab'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'yolo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'web', 'acme'),
                os.path.join(BASE_DIR, 'web', 'diag'),
                os.path.join(BASE_DIR, 'web', 'demo')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CRONJOBS = [
    ('* * * * *', 'yolo.cron.ScheduleJob')
]
WSGI_APPLICATION = 'yolo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "..", "..", "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "web", "static"),
]

if DEBUG:
    MEDIA_ROOT = os.path.join(BASE_DIR, "..", 'media')
else:
    MEDIA_ROOT = os.path.join(BASE_DIR,"..", "..", 'media')

FILE_UPLOAD_PERMISSIONS = 0o644

if(MEDIA_ROOT[-1] != SLASH):
    MEDIA_ROOT += SLASH

EXCEL_TEMPLATE = os.path.join(BASE_DIR, 'excel')
MEDIA_URL = '/media/'
DATA_UPLOAD_MAX_MEMORY_SIZE = None

MONGODB_HOST        =  DB_SETTING["host"]
MONGODB_USER        =  DB_SETTING["user"]
MONGODB_PASSWD      =  DB_SETTING["password"]
MONGODB_NAME        =  DB_SETTING["db_name"]

MONGODB_CONNECT_STR = 'mongodb://{}:{}@{}/{}'.format( MONGODB_USER     \
                                                     ,MONGODB_PASSWD \
                                                     ,MONGODB_HOST    \
                                                     ,MONGODB_NAME)


#connect(MONGODB_NAME, host=MONGODB_CONNECT_STR)
CORS_ORIGIN_ALLOW_ALL = True

EMAIL_SETTINGS = SETTINGS["email"]
EMAIL_HOST = EMAIL_SETTINGS["host"]
EMAIL_PORT = EMAIL_SETTINGS["port"]
EMAIL_HOST_USER = EMAIL_SETTINGS["user"]
EMAIL_HOST_PASSWORD = EMAIL_SETTINGS["password"]
EMAIL_SENDER = EMAIL_SETTINGS["from_email"]
#EMAIL_USE_SSL=True
EMAIL_USE_TLS=True

FACE_MIN_SIZE = SETTINGS["face_min_size"]
OS_PASSWORD = SETTINGS["os_password"]

MODEL_GENDER = None
#MODEL_GENDER = load_model(os.path.join(BASE_DIR, "api", "model_gender.h5"))


HOST = "http://localhost"

OPTIONS = {}
OPTIONS["limit_appear"] = False


# MkDir(os.path.join(MEDIA_ROOT, "find"))

ENABLE_CHECK_ANGLE = False
ENABLE_CHECK_YOLO = True
ENABLE_CHECK_BRIGHTNESS = True
ENABLE_CHECK_BLUR = False
AUTO_ADD_FACE_SAMPLE = True

CONF_THRES = 0.5
IOU_THRES = 0.5

NUM_THREAD = 4